name: master
on: 
  push:
    branches: [ master ]
permissions:
  contents: write
  id-token: write

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install npm
      run: npm install -g npm@8
    - name: Install and Build
      run: |
        npm ci
        npm run build
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2      
      with:
        name: pages
        path: artifacts/dist
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        single-commit: true
  
